prog:Karim_Akkari_1A30.o main.o
	gcc Karim_Akkari_1A30.o main.o -o prog -lSDL -lSDL_image  -lSDL_mixer -lSDL_ttf -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image  -lSDL_mixer -lSDL_ttf -g 
benaoun_et3_Multijoueur.o:benaoun_et3_Multijoueur.c
	gcc -c benaoun_et3_Multijoueur.c -lSDL -lSDL_image  -lSDL_mixer -lSDL_ttf -g
